config/routes.rb
Rails.application.routes.draw do

  get 'orders/index'

  get 'orders/create'

  get 'orders/destroy'

  get 'orders/quote'



  devise_for :users, controllers: {
    registrations: 'user/registrations',
    sessions: 'user/sessions'
  }



  resources :products do

    resources :orders, only: :create do
      collection do
        post 'session_quote'
      end
    end

    collection { post :import }

    resources :photos, only: [:create, :destroy]

    member do
      get 'download_ficha'
      get 'download_autocad'
    end
  end

  resources :orders, only: [:index, :destroy] do
    member do
      post 'update_quiantity'
    end
  end

  resources :catalogos, only: [:create, :update] do
    collection do
      get 'download_catalogo'
    end
  end

  get 'pages/index'

  get 'pages/catalogue'

  get 'pages/about'

  get 'pages/contact'

  post 'pages/message'

  get 'admin/dashboard'

  get 'admin/catalogo'

  get 'admin/import'

  get 'pages/mh3'

  root 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_adminnavbar.html.erb
<nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="#">
    <%= image_tag 'logo.png', class: 'logo', style: "width: 10rem;" %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= admin_dashboard_path %>">Dashboard</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= new_product_path %>">Agregar Producto</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= admin_import_path %>">Importar desde CSV</a>
      </li>
      <li class="nav-item">
        <%= link_to 'actualizar catalogo', admin_catalogo_path, class:'nav-link' %>
      </li>
    </ul>
    <ul class="narbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'cerrar sesión', destroy_user_session_path, method: :delete, class:'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_footer.html.erb
<footer class="container-fluid mt-3">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <ul>
        <a href=""><li>Page1</li></a>
        <a href=""><li>Page2</li></a>
        <a href="">
          <li>Productos
            <ul>
              <a href=""><li>Categoria 1</li></a>
              <a href=""><li>Categoria 1</li></a>
              <a href=""><li>Categoria 1</li></a>
              <a href=""><li>Categoria 1</li></a>
            </ul>
          </li>
        </a>
        <a href=""><li>Contacto</li></a>
      </ul>
    </div>
    <div class="col-md-4 logo-box  align-self-center">
      <img src="img/logo.png" class="footer-logo" alt="">
    </div>
  </div>
</footer>

app/views/shared/_footer2.html.erb
<div class="container p-0">
  <footer class="mainfooter mt-3" role="contentinfo">
    <div class="footer-top p-y-2">
      <div class="container-fluid">
      </div>
    </div>
    <div class="footer-middle">
      <div class="container">
        <div class="row d-flex align-items-stretch">

          <div class="col-md-4 d-flex align-items-center colum-a ">
            <!--Column1-->
            <div class="footer-pad">
              <h3>Home</h3>
              <ul class="list-unstyled">
                <a href="<%= root_path %>">
                  <li>Inicio</li>
                </a>
                <a href="<%= pages_about_path %>">
                  <li>Sobre Ox</li>
                </a>
                <a href="<%= pages_catalogue_path %>">
                  <li>Catalogo</li>
                </a>



                <li>
                  <% if @catalogo %>
                  <a href="<%= @catalogo.url.url %>" target="_blank">
                    <div class="button-download-pdf">
                      Catalogo<i class="ml-1 fas fa-chevron-down"></i>
                    </div>
                  </a>
                  <% else %>
                  <a href="#">
                    <div class="button-download-pdf">
                      Catalogo<i class="ml-1 fas fa-chevron-down"></i>
                    </div>
                  </a>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>


          <div class="col-md-4 d-flex align-items-center colum-b ">
            <!--Column1-->
            <div class="footer-pad">
              <a class="navbar-brand" href="<%= root_path %>">
                <%= image_tag 'logo.png', class: '' %>
              </a>

            </div>
          </div>




          <div class="col-md-4 d-flex align-items-center p-2 colum-c">
            <!--Column1-->
            <div class="footer-pad">
             <h3>Contacto</h3>
              <ul class="list-unstyled">
                <li><h6>TELÉFONOS<i class="fas fa-phone-square ml-2"></i></h6></li>
                <li class="">+56 9 4999 4203</li>
                <br>
                <li><h6>CORREO <i class="far fa-envelope-open ml-2"></i></h6></li>

                <li class="">ox@oxchile.com</li>
              </ul>

            </div>
          </div>



        </div>
      </div>
    </div>
    <div class="footer-bottom">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-md-6">
            <!--Footer Bottom-->
            <p class="text-xs-center">&copy; Copyright 2018 - Ox Chile</p>
          </div>
          <div class="col-xs-12 col-md-6">
             <ul class="logos-footer">
                <li>

                    <figure class="figure">
                      <%= image_tag 'Logo-02.png', class: 'figure-img img-fluid ', width:'80rem' %>
                    </figure>
                </li>
                <li>
                  <a href="http://lumichile.com/" target="_blank">
                    <figure class="figure ">

                        <%= image_tag 'lumi-f.png', class: 'figure-img img-fluid ', width:'80rem' %>

                    </figure>
                  </a>
                </li>
              </ul>

          </div>
        </div>
      </div>
    </div>
  </footer>
</div>

<script>
  if ('<%= params[:controller] %>/<%= params[:action] %>'== 'pages/index') {
    $('a[href="/"]').parent('li').addClass('active');
  }else {
    $('a[href="/<%= params[:controller] %>/<%= params[:action] %>"]').parent('li').addClass('active');
  }
</script>

app/views/shared/_lumi.html.erb
<div class="container ">
  <div class="row">
    <div class="col-md-12 no-pad mt-3 elegant parent-link">
      <div class="link-to-projects">
        <figure class="figure">
          <%= image_tag 'slide13.png', class: 'img-fluid' %>
          <a href="http://lumichile.com/" target="_blank">
            
            <figcaption class="figure-caption lumi-link row">
              <ul>
                <li class="pl-5">
                  <h5>Otra empresa </h5>
                </li>
                <li class="pl-5">
                  <figure class="figure">
                    <%= image_tag 'logomh3.png', class: 'figure-img img-fluid', width:'90rem' %>
                  </figure>

                </li>
                <li class="pl-5">
                  <button class="btn btn-outline-warning btn-lg">
                    Ver Mas
                  </button>
                  
                </li>
              </ul>

            </figcaption>
          </a>
        </figure>
      </div>
    </div>
  </div>
</div>

app/views/shared/_mh3-navbar.html.erb
<div class="container header ">
    <div class="row ">

      <div class="col-md-12 text-center">
        <div class="w-100 text-center p-1">
          <%= image_tag 'Logo-02.png', class: 'logo' %>
        </div>
      </div>

    </div>
  </div>


<nav class="container navbar navbar-expand-lg navbar-dark ">

  

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="<%= root_path %>">Ox</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="https://www.lumichile.com/">Lumi</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="<%= pages_catalogue_path %>">Contacto</a>
                  </li>
                  <li class="nav-item">
                    <% if current_user.present? %>
                      <a class="btn btn-secondary text-light">
                        Productos <span class="badge badge-light" id="product-num">0</span>
                      </a>
                    <% end %>
                  </li>
                </ul>

            </div>

      </div>
    </div>
  </div>
  


</nav>

app/views/shared/_navbar.html.erb
<div class="container header ">
    <div class="row ">

      <div class="col-md-12 text-center">
        <div class="w-100 text-center p-1">
          <%= image_tag 'logosmall.png', class: 'logo' %>
        </div>
      </div>

    </div>
  </div>


<nav class="container navbar navbar-expand-lg navbar-dark ">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="<%= root_path %>">Home </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="<%= pages_about_path %>">Sobre Ox</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="<%= pages_catalogue_path %>">Catalogo</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="<%= pages_contact_path %>">Contacto</a>
                  </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a href="<%= orders_path %>" class="nav-link  mr-2">Cotizaciones</a>
                  </li>
                  <% if current_user.present? %>
                    <%= link_to 'Cerrar Sesión', destroy_user_session_path, class:'btn btn-secondary',method: :delete %>
                  <% else %>
                  <li class="nav-item">
                    <a href="<%= new_user_registration_path %>" class="nav-link ">Registrate</a>
                  </li>
                  <li class="nav-item">
                    <a href="<%= new_user_session_path %>" class="nav-link btn btn-outline-secondary ml-2">Iniciar Sesión</a>
                  </li>
                  <% end %>
                </ul>

            </div>

</nav>