config/routes.rb
Rails.application.routes.draw do

  get 'orders/index'

  get 'orders/create'

  get 'orders/destroy'

  get 'orders/quote'



  devise_for :users, controllers: {
    registrations: 'user/registrations',
    sessions: 'user/sessions'
  }



  resources :products do

    resources :orders, only: :create do
      collection do
        post 'session_quote'
      end
    end

    collection { post :import }

    resources :photos, only: [:create, :destroy]

    member do
      get 'download_ficha'
      get 'download_autocad'
    end
  end

  resources :orders, only: [:index, :destroy] do
    member do
      post 'update_quiantity'
    end
  end

  resources :catalogos, only: [:create, :update] do
    collection do
      get 'download_catalogo'
    end
  end

  get 'pages/index'

  get 'pages/catalogue'

  get 'pages/about'

  get 'pages/contact'

  post 'pages/message'

  get 'admin/dashboard'

  get 'admin/catalogo'

  get 'admin/import'

  get 'pages/mh3'

  root 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :product 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :set_num, except: :destroy


  def index
    if current_user.present?
      @orders = Order.where(user_id: current_user.id, payed: false).order(:id)
    else
      @orders = Order.where(session: session.id, payed: false).order(:id)
    end

  end

  def create
    session[:orders] ||= []
    @product = Product.find(params[:product_id])
    if current_user.present?
      @order = Order.find_or_create_by(user_id: current_user.id, product_id: @product.id, payed: false)
      @order.quantity += 1
      @order.save
    else
      @order = Order.find_or_create_by(session: session.id, product_id: @product.id, payed: false)
      @order.quantity += 1
      @order.save
    end
  end

  def update_quiantity
    @order = Order.find(params[:id])
    @order.quantity = params[:quantity]
    @order.save
    redirect_to orders_path
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  def quote
    UserMailer.quotation(current_user).deliver_now
    @orders = Order.where(user_id: current_user.id, payed: false)
    @orders.update_all(payed: true)
    redirect_to root_path, notice: 'tu cotización se envío te responderemos a la brevedad'
  end



  private
    def set_num
      if current_user.present?
        @total = Order.where(user_id: current_user.id, payed: false).inject(0) { |sum, order| sum += (order.quantity.to_i * order.product.price.to_i) }
      else
        @total = Order.where(session: session.id, payed: false).inject(0) { |sum, order| sum += order.quantity.to_i * order.product.price.to_i }
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.js.erb
new Noty({
  type: 'success',
  text: 'El producto fue agregado correctamente',
  timeout: 1000
}).show();

app/views/orders/index.html.erb
<%= render 'shared/navbar' %>

<div class="container text-white">
  <% if @orders.size == 0 %>
    <h4>No tienes productos para cotizar</h4>
    <h5>vuelve al catalogo para agregar <%= link_to 'catalogo', pages_catalogue_path %></h5>
  <% else %>
  <div class="container text-light mt-5">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Codigo</th>
          <th>Nombre</th>
          <th>Cantidad</th>
          <th>Precio Unitario</th>
          <th>Subtotal</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= order.product.cod %></td>
            <td><%= order.product.tipo %></td>
            <td>
              <%= form_tag update_quiantity_order_path(order.id) do %>
                <%= number_field_tag :quantity, order.quantity.to_i %>
                <!-- <input type="number" name="quantity" value="<%#= order.quantity %>"> -->
              <% end %>
            </td>
            <td>$<%= number_to_currency order.product.price, unit: "", separator: ".", precision: 0 %></td>
            <td>$<%= number_to_currency order.product.price.to_i * order.quantity.to_i, unit: "", separator: ".", precision: 0 %></td>
            <td><%= link_to 'Borrar', order_path(order), method: :delete, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>Total: $<%= number_to_currency @total, unit: "", separator: ".", precision: 0 %></td>
        </tr>
      </tbody>
    </table>
    <div class="row">
      <div class="col-sm-3 offset-sm-9">
        <% if current_user.present? %>
        <%= link_to 'Cotizar', orders_quote_path, class: 'btn btn-secondary mb-5' %>
        <% else %>
        <%= link_to 'Registrate para cotizar', new_user_registration_path, class: 'btn btn-secondary mb-5' %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>