config/routes.rb
Rails.application.routes.draw do

  get 'orders/index'

  get 'orders/create'

  get 'orders/destroy'

  get 'orders/quote'



  devise_for :users, controllers: {
    registrations: 'user/registrations',
    sessions: 'user/sessions'
  }



  resources :products do

    resources :orders, only: :create do
      collection do
        post 'session_quote'
      end
    end

    collection { post :import }

    resources :photos, only: [:create, :destroy]

    member do
      get 'download_ficha'
      get 'download_autocad'
    end
  end

  resources :orders, only: [:index, :destroy] do
    member do
      post 'update_quiantity'
    end
  end

  resources :catalogos, only: [:create, :update] do
    collection do
      get 'download_catalogo'
    end
  end

  get 'pages/index'

  get 'pages/catalogue'

  get 'pages/about'

  get 'pages/contact'

  post 'pages/message'

  get 'admin/dashboard'

  get 'admin/catalogo'

  get 'admin/import'

  get 'pages/mh3'

  root 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<%= render 'shared/navbar' %>


<div class="container about-container mt-3">
	<div class="row elegant">
		<div class="offset-md-1 col-md-7 about-info mt-3">
			<p>
				<h3>Sobre Ox</h3>
				<br>
				Es una empresa de importación y comercialización de accesorios, principalmente de acero
				inoxidable que se incorporan en baños, cocinas y otros espacios de una vivienda, tales como
				barras de closet, topes de puerta, etcétera. La idea es que los espacios donde vivimos cuenten con
				“comodidades utilitarias” que nos ayuden a vivir un día a día más ordenado y organizado de
				manera orgánica y natural.

				<br><br>

				La idea nace de otro emprendimiento llamado Lumi Limitada, la cual lleva un par de años de
				funcionamiento, y que importa y comercializa luminarias, especialmente para el rubro
				inmobiliario. Viendo la experiencia de Lumi nos pudimos percatar de la necesidad las empresas
				constructoras de contar con proveedores que les den atención personalizada, no sólo luminarias
				para sus proyectos, sino también de otros accesorios que podemos encontrar en baños, cocinas,
				closet, etc. pero con un servicio de venta y postventa dedicado. Entonces se nos ocurrió crear un
				grupo, grupo MH3, para poder desarrollar ventajas competitivas y economías de escala tanto en la
				atención a clientes, publicidad, logística, procesos de importación y búsqueda de proveedores.

				<br><br>
				<h3>Calidad y Compromiso</h3>

				<br>

				Ponemos mucho foco en la calidad del producto y en el servicio que entregamos al cliente. Nos
				tomamos muy en serio los plazos estipulados, además de un servicio rápido y sin tropiezos tanto
				en venta como postventa.
			</p>
			<a href="https://www.asech.cl/noticias/entrevista-alejandro-huberman-socios-fundador-ox-limitada/" target="_blank">
				<button class="mb-3 btn btn-outline-success">Leer Entrevista</button>
				<figure class="figure ">
				<%= image_tag 'asech-logo.png', class: 'figure-img img-fluid ' %>
				</figure>


			</a>
		</div>
		<div class="col-md-4 mt-3 middle-align ">
			<figure class="figure ">
				<%= image_tag 'logo.png', class: 'figure-img img-fluid ' %>
			</figure>

		</div>
	</div>
</div>

app/views/pages/catalogue.html.erb
<%= render 'shared/navbar' %>
<div class="mr-top">





  <div class="container cat-menu mr-top">
  <div class="row">
    <!-- <div class="col-md-3 menu-cat-col">
      <h3> Categorías</h3>
      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="customCheck1">
        <label class="custom-control-label" for="customCheck1">Categoria 1</label>
      </div>

      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="customCheck2">
        <label class="custom-control-label" for="customCheck2">Categoria 2</label>
      </div>

      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="customCheck3">
        <label class="custom-control-label" for="customCheck3">Categoria 1</label>
      </div>

      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="customCheck4">
        <label class="custom-control-label" for="customCheck4">Categoria 1</label>
      </div>
    </div> -->
  </div>
  </div>

  <div class="container mr-top w-body ">
    <div class="row">

       <div class="offset-md-2 col-md-10">
          <div class="row">
            <% @products.each do |product| %>
              <div class="p-1 d-flex aligns-item-strech">
                <div class="card mr-top align-top" style="width: 19rem;">
                  <div class="card-img-box" style="background-image:url('<%= product.photos.first.image %>')">

                  </div>
                  <!--<%= image_tag product.photos.first.image, class: 'card-img-top' %>-->
                  <div class="card-body d-flex align-items-end">
                    <div class="">
                      <h5 class="card-title"><%= product.tipo %></h5>
                      <p class="card-text"><%= product.descripcion %></p>
                      <div class="text-right">
                        <%= link_to 'ver', product_path(product), class: 'btn btn-secondary text-white' %>
                        <%= link_to '+', product_orders_path(product.id), data: { remote: true, method: :post }, class: 'btn btn-success text-white' %>
                      </div>

                    </div>

                  </div>
                </div>
              </div>


            <% end %>

          </div>

      </div>
    </div>
  </div>

</div>

app/views/pages/contact.html.erb
<%= render 'shared/navbar' %>

<div class="container about-container mt-3">
	<div class="row elegant">
		<div class="offset-md-1 col-md-7 about-info mt-3">
      <h3>Contactanos</h3>
      <%= form_tag pages_message_path do  %>
          <div class="row">
            <div class="col-lg-6">
              <div class="form-group">
                <input type="text" class="form-control mt-2" placeholder="Nombre" name="name" required>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="form-group">
                <input type="text" class="form-control mt-2" placeholder="Empresa" name="company" required>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="form-group">
                <input type="email" class="form-control mt-2" placeholder="Email" name="mail" required>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="form-group">
                <input type="number" class="form-control mt-2" placeholder="Teléfono" name="phone" required>
              </div>
            </div>
            <div class="col-12">
              <div class="form-group">
                <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="Mensaje" rows="3" name="message" required></textarea>
              </div>
            </div>
            <div class="col-12">
            </div>
            <div class="col-12">
              <button class="btn btn-light" type="submit">Enviar</button>
            </div>
          </div>
        <% end %>
		</div>
		<div class="col-md-4 mt-3 middle-align ">
			<figure class="figure ">
				<%= image_tag 'logo.png', class: 'figure-img img-fluid ' %>
			</figure>

		</div>
	</div>
</div>

app/views/pages/index.html.erb
    <%= render 'shared/navbar' %>


<div id="carouselExampleIndicators" class="container carousel slide p-0" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'slide10.png', class: 'd-block w-100' %>
      <div class="carousel-caption d-none d-md-block">

        <div class="container">
          <div class="row">

            <div class="offset-md-4 col-md-4 text-center ">
                <figure class="figure">
                  <%= image_tag 'iso.png', class: '' %>
                </figure>
                <p class="text-center">
                   Acero inoxidable, aluminio, comodidad en el hogar, seguridad vial
                </p>

            </div>
          </div>
        </div>
      </div>
    </div>



    <div class="carousel-item">
      <%= image_tag 'slide12.png', class: 'd-block w-100' %>
      <div class="carousel-caption d-none d-md-block">

        <div class="container">
          <div class="row">

            <div class="offset-md-4 col-md-4 text-center ">
                <figure class="figure">
                  <%= image_tag 'Logo-02.png', class: '' %>
                </figure>
                <p class="text-center">
                   Enfocado en entregar lo mejor en construcción
                </p>
                <figure class="figure">
                  <a href="http://lumichile.com/"><%= image_tag 'lumi.png', class: '' %></a>

                  <%= image_tag 'logosmall.png', class: '' %>
                </figure>
            </div>
          </div>
        </div>
      </div>
    </div>
        <div class="carousel-item">
      <%= image_tag 'slide13.png', class: 'd-block w-100' %>
      <div class="carousel-caption d-none d-md-block">

        <div class="container">
          <div class="row">

            <div class="offset-md-4 col-md-4 text-center ">

                <p class="text-center">
                   Iluminación para construcción y paisajismo.
                </p>
                <a class="http://lumichile.com/" href="#">
                 <button class="btn btn-warning">Ver Más</button>
                </a>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container test-flex">



  <div class="row mt-2 product-carousel ">
    <div class="col-md-3 no-pad parent-link mt-2">
      <div class="image-wrapper bkg-full-pro bkg-1 link-to-projects ">

              <%= image_tag 'index-cat1.png', class: 'link-img img-fluid   align-middle ghost ' %>
              <h3 class="">
                Catálogo
                <a class="" href="<%= pages_catalogue_path %>">
                 <button class="btn btn-outline-success">Ver Más</button>
                </a>

              </h3>
          </div>
    </div>



    <div class="col-md-9 p-0 carousel-pro-box">
      <div class="carousel-pro d-flex align-items-stretch h-100">
        <% @products.each do |product| %>
          <div class="pro-box d-flex align-items-end" style="background-image:url('<%= product.photos.first.image %>'); height: 100% !important; ">
            <div class="caption-product">
              <h5><%= product.tipo %></h5>
              <%= link_to 'ver', product_path(product), class: 'btn btn-secondary text-white' %>
            </div>

          </div>
        <% end %>
      </div>
    </div>

    <!--<div class="col-md-3 parent-link">
      <figure class="figure">


        <div class="image-wrapper link-to-projects" >
          <%= image_tag 'index-cat1.png', class: 'm-2 elegant img-fuild ', style: 'width: 100%'%>
          <a href="<%= pages_catalogue_path %>">
            <h4>Ver Producto</h4>
          </a>
        </div>

      </figure>
    </div>

    <div class="col-md-3 parent-link">
      <div class="image-wrapper link-to-projects" >
        <%= image_tag 'index-cat2.png', class: 'm-2 elegant img-fuild ', style: 'width: 100%'%>
        <a href="<%= pages_catalogue_path %>">
          <h4>Ver Producto</h4>
        </a>
      </div>
    </div>
    <div class="col-md-3 parent-link">
      <div class="image-wrapper link-to-projects" >
        <%= image_tag 'index-cat3.png', class: 'm-2 elegant img-fuild ', style: 'width: 100%'%>
        <a href="<%= pages_catalogue_path %>">
          <h4>Ver Producto</h4>
        </a>
      </div>
    </div>-->

  </div>
</div>

<script>

  $('.carousel-pro').slick({

      slidesToShow: 3,
      slidesToScroll: 1,
      arrows: false,


      pauseOnHover: true,

      autoplay: true,
      autoplaySpeed: 3000



    })
  $( "div.slick-slide > div" ).css( "height", "100%" );


</script>

app/views/pages/mh3.html.erb
<%= render 'shared/mh3-navbar' %>

<div class="container mt-3">

	<div class="row d-flex align-items-stretch">
		<div class="col-md-6 p-0">
			<div class="mh3-menu w-100 lumi-select ">
				<div class="caption-mh3-menu text-center">
					<%= image_tag 'logo.png', class: 'logo' %>
					<p>Acero inoxidable, aluminio, comodidad en el hogar.</p>
				</div>
			</div>
		</div>
		<div class="col-md-6 p-0">
			<div class="mh3-menu w-100 ox-select ">
				<div class="caption-mh3-menu text-center">
					<%= image_tag 'lumi.png', class: 'logo' %>
					<p>Iluminación para construcción y paisajismo.</p>
				</div>
			</div>
		</div>
	</div>

	
	
</div>