config/routes.rb
Rails.application.routes.draw do

  get 'orders/index'

  get 'orders/create'

  get 'orders/destroy'

  get 'orders/quote'



  devise_for :users, controllers: {
    registrations: 'user/registrations',
    sessions: 'user/sessions'
  }



  resources :products do

    resources :orders, only: :create do
      collection do
        post 'session_quote'
      end
    end

    collection { post :import }

    resources :photos, only: [:create, :destroy]

    member do
      get 'download_ficha'
      get 'download_autocad'
    end
  end

  resources :orders, only: [:index, :destroy] do
    member do
      post 'update_quiantity'
    end
  end

  resources :catalogos, only: [:create, :update] do
    collection do
      get 'download_catalogo'
    end
  end

  get 'pages/index'

  get 'pages/catalogue'

  get 'pages/about'

  get 'pages/contact'

  post 'pages/message'

  get 'admin/dashboard'

  get 'admin/catalogo'

  get 'admin/import'

  get 'pages/mh3'

  root 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
require 'csv'
class Product < ApplicationRecord
  has_many :photos, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :users, through: :orders, dependent: :destroy
  mount_uploader :ficha, ImageUploader
  mount_uploader :autocad, ImageUploader
  
  def self.import(file)
    CSV.foreach(file.path, headers: true,
                           col_sep: ',',
                           header_converters: :symbol) do |row|

      product = Product.find_by(cod: row[:cod]) || new
      product.attributes = row.to_hash
      product.save
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :download_ficha, :download_autocad]
  before_action :authenticate_user!, except: [:show, :download_ficha, :download_autocad]
  layout 'admin', except: [:index, :show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @catalogo = Catalogo.last
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to edit_product_path(@product), notice: 'Product was successfully updated.' }
        format.json { render :edit, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Product.import(params[:file])
    redirect_to root_path
  end

  def download_ficha
    image = @product.ficha
    if image.try(:file).exists?
      data = open(image.url)
      send_data data.read, type: data.content_type, x_sendfile: true, filename: @product.ficha.url.split('/')[7].split('?')[0]
    end
  end

  def download_autocad
    cad = @product.autocad
    if cad.try(:file).exists?
      data = open(cad.url)
      send_data data.read, type: data.content_type, x_sendfile: true, filename: @product.autocad.url.split('/')[7].split('?')[0]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:cod, :tipo, :descripcion, :medidas, :material, :proveedor, :codigo_provedor, :precio_usa, :price, :ficha, :autocad)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cod %>
    <%= form.text_field :cod, id: :product_cod %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :product_tipo %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :product_descripcion %>
  </div>

  <div class="field">
    <%= form.label :medidas %>
    <%= form.text_field :medidas, id: :product_medidas %>
  </div>

  <div class="field">
    <%= form.label :material %>
    <%= form.text_field :material, id: :product_material %>
  </div>

  <div class="field">
    <%= form.label :proveedor %>
    <%= form.text_field :proveedor, id: :product_proveedor %>
  </div>

  <div class="field">
    <%= form.label :codigo_provedor %>
    <%= form.text_field :codigo_provedor, id: :product_codigo_provedor %>
  </div>

  <div class="field">
    <%= form.label :precio_usa %>
    <%= form.text_field :precio_usa, id: :product_precio_usa %>
  </div>


  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :ficha %>
    <%= form.file_field :ficha %>
  </div>

  <div class="field">
    <%= form.label :autocad %>
    <%= form.file_field :autocad %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>



<h2>Imagenes</h2>
<%= form_with model: [@product, Photo.new], local: true do |f| %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>


<div class="row">
  <% @product.photos.each do |photo| %>
  <div class="col-md-4">
    <%= image_tag photo.image, width: '200px' %>
    <%= link_to 'x', product_photo_path(@product, photo), method: :delete, class:'btn btn-danger btn-sm' %>
  </div>
  <% end %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Cod</th>
      <th>Tipo</th>
      <th>Descripcion</th>
      <th>Medidas</th>
      <th>Material</th>
      <th>Proveedor</th>
      <th>Codigo-provedor</th>
      <th>Precio-usa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.cod %></td>
        <td><%= product.tipo %></td>
        <td><%= product.descripcion %></td>
        <td><%= product.medidas %></td>
        <td><%= product.material %></td>
        <td><%= product.proveedor %></td>
        <td><%= product.codigo_provedor %></td>
        <td><%= product.precio_usa %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>


<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= render 'shared/navbar' %>
<div class="container product-show mt-3 elegant">

	<div class="row product-show  mt-3 mb-3">


	  <div class="col-md-5 ">
	    <div class="sp-loading"><%= image_tag 'sp-loading.gif' %><br>Cargando imagenes</div>
	    <div class="sp-wrap">
	      <% @product.photos.each do |photo| %>
	    	  <a href="<%= photo.image %>"><%= image_tag photo.image %></a>
	      <% end %>
	    </div>
	  </div>

	  <div class="col-md-7 ">

	  	<ul class="list-group">
			<li class="list-group-item">
			  	<h5>Tipo:</h5>
			  	<p class='product-title-show'>
			  		<%= @product.tipo %>
			  	</p>


			  	</li>
		  <li class="list-group-item">
		  	<h5>Descripcion</h5>
		  	<%= @product.descripcion %></li>
		  <li class="list-group-item">
		  	<h5>Medidas</h5>
		  	<%= @product.medidas %></li>
		  <li class="list-group-item">
		  	<h5>Material</h5>
		  	<%= @product.material %></li>
		  	<li class="list-group-item">
		  	<h5>Cod</h5>
		  	<%= @product.cod %></li>
		  	 <li id="precio" class="list-group-item text-right precio">
			  	<h5>Precio</h5>
			  	<%= @product.price %>
			 </li>


		  	<li class="list-group-item text-right">
		  		<%= link_to download_ficha_product_path(@product) do %>
		  			<button class="btn btn-primary  btn-success">
		  				Descargar Ficha
		  			</button>
		  		<% end %>

					<% if @product.autocad.present? %>
					  <%= link_to 'Descargar Autocad', download_autocad_product_path(@product), class:'btn btn-primary btn-success' %>
					<% end %>
		  		<a class="" href="<%= pages_catalogue_path %>">
					<button class="btn btn-primary  btn-success">
						Catalogo
					</button>
				</a>
		  	</li>
		</ul>

	  </div>
	</div>



</div>
<script type="text/javascript">
	$('.nav-link[href="/pages/catalogue"]').parent('li').addClass('active');
</script>